"""document regions: structured page annotations

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-31

PURELY ADDITIVE
---------------
One new table. Nothing existing is altered, and in particular the crop
workflow is untouched: `QuestionResponse.ans_*_images` and
`Question.ms_*_images` keep their JSON path lists, and existing cropped images
keep working with no region rows at all. A deployment can upgrade and carry on
using the old editor.

WHY A TABLE RATHER THAN MORE COLUMNS
------------------------------------
A crop is one image per bucket per question. A region is a many-per-page,
many-per-question, many-per-document thing with its own lifecycle, so it needs
rows. Adding more JSON columns to `question_responses` would have kept the
structure the crop workflow already fails to represent -- page identity,
geometry, ordering, provenance -- inside an opaque string.

`question_id` is `ON DELETE SET NULL`, not CASCADE: an unassigned region is a
legitimate state (see backend/regions/schema.py), so deleting a question should
orphan its regions rather than destroy the student work they point at. Every
other foreign key cascades, matching the rest of the schema.

Downgrade drops the table, losing only annotations -- no marks, no crops, no
student work.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('answer_script_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('region_type', sa.Text(), nullable=False),
    sa.Column('geometry_kind', sa.Text(), nullable=False),
    sa.Column('geometry', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('question_part', sa.Text(), nullable=True),
    sa.Column('reading_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('provider_metadata', sa.Text(), nullable=True),
    sa.Column('crop_path', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['answer_script_id'], ['answer_scripts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_regions_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_regions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_regions_id'))
        batch_op.drop_index(batch_op.f('ix_document_regions_exam_id'))

    op.drop_table('document_regions')
    # ### end Alembic commands ###
